### ISSUE TITLE
New Library and prepare scripts for developer

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#383]
We plan to implement ready-use scripts using in hackathon.

Every ticket in this topic include 

- Implement rust library (How to get and parse of data source)
   - [ ] Define how to get data (curl to endpoint for now)
   - [ ] Define how to parse raw data to meaningful data use in logic script

- Define specification of script
  - [ ] Input -> Parameter of script
  - [ ] Output -> Result of script

- Implement script to store in chain follow specification
